---
services:
  meta_storage:
    image: bitnami/postgresql:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - "POSTGRESQL_DATABASE=medol"
      - "POSTGRESQL_USERNAME=${DB_USER}"
      - "POSTGRESQL_PASSWORD=${DB_PASSWORD}"
    volumes:
      - metadata:/bitnami/postgresql
  frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"

volumes:
  metadata:
