---
services:
  meta_storage:
    image: bitnami/postgresql:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - "POSTGRESQL_DATABASE=medol"
      - "POSTGRESQL_USERNAME=${DB_USER}"
      - "POSTGRESQL_PASSWORD=${DB_PASSWORD}"
    volumes:
      - metadata:/bitnami/postgresql
  storage:
    image: bitnami/minio:latest
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/bitnami/minio/data
  frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"

volumes:
  metadata:
  minio_storage:
